name: practice workfow  
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step 
        run: echo "Building Project"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: echo "Testing Project"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploying Project"
