name: sequential job #name of the workflow
on: workflow_dispatch #trigger like on which action this workflow should get trigger like here it is manual trigger

jobs: # jobs keyword to define job
  build: #job name
    runs-on: ubuntu-latest # on which platform the job will run
    steps: #using steps keyword to define the steps
      - name: build step # step name
        run: echo "building the project" # defining the command which will run on this step

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test step
        run: echo "testing the project"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy step
        run: echo "Deploying the project"
