name: Vars And Secrets
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step 
        run: echo "I am ${{vars.TEST_VAR}} King Of Hell" #by ${{vars.TEST_VAR}} we are accessing the global variable we added in our repository, follow this exact syntax to get the value of the variable